### PR TITLE
Add rustupComponents argument

### PR DESCRIPTION
**Pull request by wfxr**
Some rust libs like [tonic](https://github.com/hyperium/tonic) requre `rustfmt` to format the generated code. So I added a `rustup-components` option to allow users to install extra rustup components.

### CODE REVIEW

**Comment by wfxr** [comment]
> I think it should be added to non-docker build too:

@messense Oh I missed that. Will add it later.

**Comment by wfxr** [comment]
@messense I'm not familiar with both github actions and typescript. Feel free to make any changes.

**Comment by messense** [comment]
I'll fix it.

**Comment by wfxr** [comment]
Ok. Thank you! I should have prepared a better ts development environment...

**Pull request merged**
